name: Deploy PR to Staging Slot

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
env:
  AZURE_WEBAPP_NAME: 'translation-api-billingportal-nlpghana' 
  SLOT_NAME: 'translation-api-billingportal-nlpghana-staging'

jobs:
  build-and-deploy-slot:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ghcr.io/ghananlp/app:pr-${{ github.event.pull_request.number }}

      - name: Deploy to Azure Web App Slot
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_BILLING_STAGING_SLOT_PUBLISH_PROFILE }}
          slot-name: ${{ env.SLOT_NAME }}
          images: 'ghcr.io/${{ github.repository }}/app:pr-${{ github.event.pull_request.number }}'